name: Build native binaries

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - '**.zig'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-build
          path: |
            zig-cache
            ~/.cache/deps-zig

      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with: {version: master}

      - run: zig build update
      - run: zig build -Drelease-safe -Dsuffix -Dstrip -Dtarget=x86_64-linux-gnu
      - run: zig build -Drelease-safe -Dsuffix -Dstrip -Dtarget=x86_64-linux-musl
      - run: zig build -Drelease-safe -Dsuffix -Dstrip -Dtarget=x86_64-windows

      - uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: zig-out/bin/slimy-*-*
